conda_env: "/home/gborrego/gborrego/AB_Multiomics_CD14_CD4/scripts/ATACpipeline-environment.yml"

raw_dir: "/media/scratch/gborrego/AB_Multiomics_CD14_CD4/CutTag/data/raw"
out_dir: "/home/gborrego/gborrego/AB_Multiomics_CD14_CD4/CutTag/data/clean"

# default should be trim_mode: "--detect_adapter_for_pe"
trim_mode: "--trim_poly_x"

bowtie2_index: "/home/gborrego/gborrego/AB_Multiomics_CD14_CD4/data/external/Homo_sapiens_hg38/GRCh38_noalt_as/GRCh38_noalt_as"
bowtie2_threads: 6 
bowtie2_spikein_index: ""

blacklist_bed: "/home/gborrego/gborrego/AB_Multiomics_CD14_CD4/data/external/ENCODE-hg38-blacklist.v2.bed"

#TSS coordinates for TSS enrichment, hg38
tss_bed: "/home/gborrego/gborrego/AB_Multiomics_CD14_CD4/data/external/hg38_tss_TableBrowser_1bp.bed" 
